lib/dixord_web/router.ex
defmodule DixordWeb.Router do
  use DixordWeb, :router
  use Pow.Phoenix.Router
  import DixordWeb.Auth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :auth do
    plug(:authenticate_user)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/" do
    pipe_through(:browser)

    pow_routes()
  end

  scope "/", DixordWeb do
    pipe_through(:browser)
    pipe_through(:auth)

    resources("/users", UserController)
    resources("/messages", MessageController)
    resources("/chats", ChatController)
    resources("/", PageController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", DixordWeb do
  #   pipe_through :api
  # end
end

lib/dixord_web/templates/page/index.html.eex
<!-- The list of messages will appear here: -->
<ul id='msg-list' style='list-style: none; min-height:200px; padding: 10px;'></ul>
<div class="row text-input">
  <div class="col-9 pr-0">
    <input type="text" id="msg" class="form-control" placeholder="Message this chat">
  </div>
  <div class="col-3 pl-0">
	<button id="send" type="button" class="btn btn-primary">Send</button>
  </div>
</div>

lib/dixord_web/templates/page/index.html.leex
<div class="row w-100 ml-0" >
  <%= render "lhc.html", assigns %>
  <div class="col-md-8">
    <ul id='msg-list' class='chatview' phx-hook="MsgList">
      <%= DixordWeb.Components.ChatDescription.render(
              assigns |> Map.put(:name, @current_chat.name)
              |> Map.put(:description, @current_chat.description)
      ) %>
      <%= for message <- @messages do %>
        <%= render "message_body.html", 
                    assigns 
                    |> Map.put(:message_content, message.content) 
                    |> Map.put(:message_inserted_at, message.inserted_at) 
                    |> Map.put(:user, message.user)
        %>
      <% end %>
    </ul>
    <div class="composer ml-3 mr-3">
      <div class="mb-1">
        <%= for user <- @users_presence do %>
          <%= if user.typing do %>
            <span class="font-weight-light text-secondary">
              <%= user.username %> is typing...
            </span>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= form_for @message, "#", [phx_change: :typing, phx_submit: :message], fn _f -> %>
          <%= text_input :message, :content, value: @message.changes[:content], phx_blur: "stop_typing", placeholder: "Message #"<>@current_chat.name, class: 'form-control' %>
          <%= submit "send", class: 'd-none' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "rhc.html", assigns %>
</div>

lib/dixord_web/templates/page/lhc.html.leex
  <div class="col-md-1 server-lhc d-none">
    <%= DixordWeb.Components.LhcServer.render(
           assigns |> Map.put(:name, "home")|> Map.put(:active, false)
    ) %>
    <div class="server-lhc-separator mt-3">
    </div>
    <%= DixordWeb.Components.LhcServer.render(
        assigns |> Map.put(:name, "Guests Server")|> Map.put(:active, true)
    ) %>
    <%= DixordWeb.Components.LhcServer.render(
        assigns |> Map.put(:name, "Elixir School")|> Map.put(:active, false)
    ) %>
    <%= DixordWeb.Components.LhcServer.render(
        assigns |> Map.put(:name, "Harvard CS50")|> Map.put(:active, false)
    ) %>
    <%= DixordWeb.Components.LhcServer.render(
        assigns |> Map.put(:name, "Andrew Ng's Machine Learning")|> Map.put(:active, false)
    ) %>
  </div>
  <div class="col-md-2 d-none d-md-block sidebar pr-0 pl-0" >
    <div class="sidebar-sticky">
      <ul class="nav flex-column lhc">
        <%= for category <- @chats do %>
          <div class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <h6 class="text-uppercase font-weight-bold mb-0">
              <%= category.category_name %>
            </h6>
            <%= link to: Routes.chat_path(@conn, :new, category_name: category.category_name), class: "d-flex align-items-center text-muted" do %>
              <svg class="addButtonIcon-3u-3Hu" aria-hidden="false" width="18" height="18" viewBox="0 0 18 18"><polygon fill-rule="nonzero" fill="currentColor" points="15 10 10 10 10 15 8 15 8 10 3 10 3 8 8 8 8 3 10 3 10 8 15 8"></polygon></svg>
            <% end %>
          </div>
          <%= for chat <- category.chats do %>
            <%= DixordWeb.Components.LhcChat.render(
               assigns
               |> Map.put(:chat, chat)
               |> Map.put(:active, chat.id == @current_chat.id)
               |> Map.put(:chat_link, Routes.chat_path(@conn, :show, chat))
               |> Map.put(:chat_edit_link, Routes.chat_path(@conn, :edit, chat))
  ) %>
          <% end %>
        <% end %>
      </ul>
      <div class="w-100 your-account-container">
      <%= if !@current_user.claimed do %>
      <div class="p-3" style="background-color:#f26522;color:white;">
        <%= link "This is an unclaimed account, claim it before it's lost.", to: Routes.pow_registration_path(@conn, :new), class: "text-white text-bold" %>
      </div>
      <div class="w-100 p-3">
        <%= render DixordWeb.PageView, "message_body.html",
              assigns
                |> Map.put(:message_content, "Temporary Account") 
                |> Map.put(:message_inserted_at, "") 
                |> Map.put(:user, @current_user)
              %>
      </div>
    <% else %>
      <div class="w-100 p-3">
        <%= render DixordWeb.PageView, "message_body.html",
              assigns
|> Map.put(:message_content, "Messages Sent: #{length(@current_user.messages)}") 
                |> Map.put(:message_inserted_at, "") 
                |> Map.put(:user, @current_user)
              %>
      </div>

      <% end %>
      </div>
    </div>
  </div>

lib/dixord_web/templates/page/rhc.html.leex
<div class="col-md-2 sidebar d-none d-md-block">
  <div class="sidebar-sticky">
      <div class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <h6 class="text-uppercase font-weight-bold mb-0">GUESTS—<%= length(@users) %></h6>
      </div>
      <ul class="nav flex-column lhc pl-3 pt-1">
          <%= for user <- @users do %>
            <%= render "message_body.html", 
                        assigns 
                        |> Map.put(:message_content, "Online") 
                        |> Map.put(:message_inserted_at, "") 
                        |> Map.put(:user, user)
            %>
          <% end %>
      </ul>
  </div>
</div>